onLoadFont errors are no longer fatal to instantiation
graphicore/specimenTools pull request #10
Opened 2016-11-10 18:07 UTC by kontur

Previously a faulty passed in font (not a opentype font, invalid file name) would cause opentype.js fail and halt script execution. I slightly modified `onLoadFont` to handle those cases more gracefully with a console error message and proceeding to still load the other fonts. Not perfect, but better than failing outright.

2016-11-10 18:25 UTC, kontur commented
One shortcoming in particular is that the fontSet originally passed in to other components is oblivious of any failed fonts.

2016-11-14 13:18 UTC, graphicore requested changes

2016-11-15 09:14 UTC, kontur commented on lib/loadFonts.js
> +        try {
`fontArrayBuffer` seems to always be an object, even if you try to load and empty url, for example. The try-catch will have populated `error` with the error opentype returns from trying to parse from a empty fontArrayBuffer.

2016-11-15 09:18 UTC, kontur commented on lib/loadFonts.js
> +        var error = !(err === null);
True; tried to force casting to a boolean, but maybe it's not needed. I'll still have the `var error = err`definition, so that an error thrown inside the try-catch can be assigned to the variable, though

2016-11-16 08:31 UTC, kontur commented
Here are different errors that are causing the confusion in structuring that function, and also in the assumption that if either error or fontArrayBuffer are not null you can assume something about the other:
* loading a resource that returns 404: error !== null, fontArrayBuffer === null
* passed in an empty string as URL: error === null, fontArrayBuffer !== null
* loading a resource that opentype.js fails to parse: error === null, fontArrayBuffer !== null, opentype.parse() will throw error

I added a check to prevent the second kind in https://github.com/graphicore/specimenTools/pull/10/commits/5059d2bc5ce5b9394d144587b99b512da1af24d0#diff-13b0f15736fe8862fee9435ca901a862R79
One question that remains for me is if ever any error !== null is passed in, won't it already be listed in the console? At least the 404 is already, but I don't know if loading from file input would be different?

2016-11-16 09:42 UTC, graphicore commented
> * passed in an empty string as URL: error === null, fontArrayBuffer !== null

...

> I added a check to prevent the second kind in 5059d2b#diff-13b0f15736fe8862fee9435ca901a862R79
One question that remains for me is if ever any error !== null is passed in, won't it already be listed in the console? At least the 404 is already, but I don't know if loading from file input would be different?

...

> `if (fontFiles[i]) {`

You don't want to silence this kind of user/input error. You could raise an error though, if you are concerned about this:

```js
if (!fontFiles[i])
    throw new Error('The url at index '+i+' appears to be invalid.');
````

2016-11-16 09:52 UTC, graphicore commented
```js
    function onLoadFont(i, fontFileName, err, fontArraybuffer) {
        /* jshint validthis: true */
        var font;
        if(!err)
            try {
                font = opentype.parse(fontArraybuffer);
            }
            catch (parseError) {
                err = parseError;
            }

        if(err) {
            console.warn('Can\'t load font', fontFileName, ' with error:', parseError);
            this.countAll--;
        }
        else {
            this.pubsub.publish('loadFont', i, fontFileName, font, fontArraybuffer);
            this.countLoaded += 1;
        }
        
        if(this.countLoaded === this.countAll)
            this.pubsub.publish('allFontsLoaded', this.countAll);

    }
```

2016-12-07 16:53 UTC, graphicore approved these changes

2016-12-07 16:54 UTC, merged